# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... => 231 or 187
# 
# Find the sum of all the even-valued terms in the sequence which do not exceed four million.

def is_odd?(n)
  (n % 2) > 0
end

def is_even?(n)
  (n % 2) == 0
end

def generate_fibonacci
  array = [1,2]
  next_number = (array[-2] + array [-1])
  while next_number < 4_000_000
    array << next_number
    next_number = (array[-2] + array [-1])
  end
  array.delete_if {|i| is_odd?(i)}
  sum = array.inject(0){|sum,item| sum + item}
end

puts generate_fibonacci